"""
threshold_robustness.py
Robustness check: sweep probability thresholds 0.50 → 0.80 (step 0.05)
for the tuned LightGBM strategy on the VU.PA test set.

Assumes `test` has columns: Date, Close, prob_up_tuned
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Load test set (already generated by backtest.py)
# ---------------------------------------------------------------------------
df_all = pd.read_csv("vu_pa_history_features_with_preds.csv", parse_dates=["Date"])
test = df_all[df_all["is_test"] == 1].sort_values("Date").reset_index(drop=True)

print(f"Test set: {test['Date'].iloc[0].date()} → {test['Date'].iloc[-1].date()}  "
      f"({len(test)} rows)\n")

# ===========================================================================
# 1. BACKTEST FUNCTION
# ===========================================================================
def backtest_for_threshold(test_df: pd.DataFrame, thr: float) -> dict:
    """
    Run a simple long-only daily strategy on test_df.

    Parameters
    ----------
    test_df : DataFrame with columns Date, Close, prob_up_tuned (sorted by Date)
    thr     : probability threshold — invest when prob_up_tuned >= thr

    Returns
    -------
    dict with keys: threshold, final_equity, total_return, max_drawdown,
                    sharpe, days_invested, invested_pct
    """
    df = test_df.sort_values("Date").copy()

    df["position"]     = (df["prob_up_tuned"] >= thr).astype(int)
    df["ret_stock"]    = df["Close"].pct_change().fillna(0.0)
    df["ret_strategy"] = df["position"].shift(1).fillna(0) * df["ret_stock"]

    equity = (1 + df["ret_strategy"]).cumprod()

    # Max drawdown
    running_max  = equity.cummax()
    drawdown     = (equity - running_max) / running_max
    max_dd       = drawdown.min()

    # Annualised Sharpe (rf = 0)
    mu    = df["ret_strategy"].mean()
    sigma = df["ret_strategy"].std()
    sharpe = (mu / sigma * np.sqrt(252)) if sigma > 0 else 0.0

    days_invested = int(df["position"].sum())
    invested_pct  = days_invested / len(df)

    return {
        "threshold":    thr,
        "final_equity": round(equity.iloc[-1], 4),
        "total_return": round(equity.iloc[-1] - 1, 4),
        "max_drawdown": round(max_dd, 4),
        "sharpe":       round(sharpe, 3),
        "days_invested": days_invested,
        "invested_pct": round(invested_pct, 4),
    }

# ===========================================================================
# 2. SWEEP THRESHOLDS 0.50 → 0.80  (step 0.05)
# ===========================================================================
thresholds = np.arange(0.50, 0.81, 0.05)
results    = [backtest_for_threshold(test, thr) for thr in thresholds]
res_df     = pd.DataFrame(results).sort_values("threshold").reset_index(drop=True)

# Format for display
display = res_df.copy()
display["total_return"] = display["total_return"].map("{:+.1%}".format)
display["max_drawdown"] = display["max_drawdown"].map("{:.1%}".format)
display["invested_pct"] = display["invested_pct"].map("{:.0%}".format)
display["final_equity"] = display["final_equity"].map("{:.3f}x".format)

print(display.to_string(index=False))

# Buy-and-hold reference
bh_equity = (1 + test["Close"].pct_change().fillna(0)).cumprod()
bh_total   = bh_equity.iloc[-1] - 1
bh_mdd     = ((bh_equity - bh_equity.cummax()) / bh_equity.cummax()).min()
bh_ret     = test["Close"].pct_change().fillna(0)
bh_sharpe  = bh_ret.mean() / bh_ret.std() * np.sqrt(252)

print(f"\nBuy & Hold reference ─── "
      f"total_return={bh_total:+.1%}  "
      f"max_drawdown={bh_mdd:.1%}  "
      f"sharpe={bh_sharpe:.3f}")

# ===========================================================================
# 3. PLOT — threshold vs total_return (%)
# ===========================================================================
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle("VU.PA — LightGBM Strategy Robustness Check (Test Set)\n"
             f"{test['Date'].iloc[0].date()} → {test['Date'].iloc[-1].date()}",
             fontsize=13, fontweight="bold")

thr_vals   = res_df["threshold"].values
ret_vals   = res_df["total_return"].values * 100        # to %
mdd_vals   = res_df["max_drawdown"].values * 100
sharpe_vals = res_df["sharpe"].values
inv_vals   = res_df["invested_pct"].values * 100

# Helper: add B&H horizontal reference line
def bh_line(ax, val, label):
    ax.axhline(val, color="steelblue", linestyle="--", linewidth=1.2, label=label)

# Panel 1 – Total return
ax = axes[0, 0]
ax.bar(thr_vals, ret_vals, width=0.03, color="tomato", edgecolor="white", alpha=0.85)
bh_line(ax, bh_total * 100, f"Buy&Hold {bh_total:+.1%}")
ax.set_xlabel("Threshold"); ax.set_ylabel("Total Return (%)")
ax.set_title("Total Return vs Threshold")
ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.3)
ax.xaxis.set_ticks(thr_vals); ax.set_xticklabels([f"{t:.2f}" for t in thr_vals])

# Panel 2 – Max Drawdown (lower is better — shown as negative)
ax = axes[0, 1]
ax.bar(thr_vals, mdd_vals, width=0.03, color="salmon", edgecolor="white", alpha=0.85)
bh_line(ax, bh_mdd * 100, f"Buy&Hold {bh_mdd:.1%}")
ax.set_xlabel("Threshold"); ax.set_ylabel("Max Drawdown (%)")
ax.set_title("Max Drawdown vs Threshold  (closer to 0 = better)")
ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.3)
ax.xaxis.set_ticks(thr_vals); ax.set_xticklabels([f"{t:.2f}" for t in thr_vals])

# Panel 3 – Sharpe ratio
ax = axes[1, 0]
ax.plot(thr_vals, sharpe_vals, marker="o", color="seagreen", linewidth=2)
bh_line(ax, bh_sharpe, f"Buy&Hold {bh_sharpe:.3f}")
ax.set_xlabel("Threshold"); ax.set_ylabel("Sharpe Ratio (ann.)")
ax.set_title("Sharpe Ratio vs Threshold")
ax.legend(fontsize=8); ax.grid(alpha=0.3)
ax.xaxis.set_ticks(thr_vals); ax.set_xticklabels([f"{t:.2f}" for t in thr_vals])

# Panel 4 – % Days Invested
ax = axes[1, 1]
ax.bar(thr_vals, inv_vals, width=0.03, color="mediumpurple", edgecolor="white", alpha=0.85)
ax.axhline(100, color="steelblue", linestyle="--", linewidth=1.2, label="Buy&Hold 100%")
ax.set_xlabel("Threshold"); ax.set_ylabel("Days Invested (%)")
ax.set_title("% Days Invested vs Threshold")
ax.legend(fontsize=8); ax.grid(axis="y", alpha=0.3)
ax.xaxis.set_ticks(thr_vals); ax.set_xticklabels([f"{t:.2f}" for t in thr_vals])

plt.tight_layout()
plt.savefig("threshold_robustness.png", dpi=150, bbox_inches="tight")
print("\nPlot saved → threshold_robustness.png")
